---
title: "In-class Exercise 5"
author: "Ha Duc Tien"
date: "May 11, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# 1. Loading R Packages for text data processing


```{r}
pacman::p_load(tidyverse, readtext, quanteda, tidytext)
```

# 2. Loading the text data

```{r}
text_data <- readtext("data/articles/*")
```

```{r}
corpus_text <- corpus(text_data)

summary(corpus_text, 5)
```

# 3. Some Text Data Processing
```{r}
usenet_words <- text_data %>%
  unnest_tokens(word, text) %>%
  filter(str_detect(word, "[a-z']$"),
         !word %in% stop_words$word)

view(usenet_words)
```


```{r}
usenet_words %>%
  count(word, sort = TRUE)
```


```{r}
text_data_splitted <- text_data %>%
  separate_wider_delim("doc_id",
                        delim = "__0__",
                        names = c("X","Y"),
                        too_few = "align_end")
```

```{r}
view(text_data_splitted)
```


# 4. Loading R packages for json data processing

```{r}
pacman::p_load(jsonlite, tidyverse)
```

# 5. Loading the json data

```{r}
mc1_data <- fromJSON("data/mc1.json")

```