---
title: "In-class Exercise 9"
author: "Ha Duc Tien"
date: "June 15, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# 1. Installing and loading R packages

```{r}
pacman::p_load(corrplot, ggstatsplot, tidyverse, 
               scatterPlotMatrix, parallelPlot, 
               cluster, Clustering, factoextra)
```

# 2. Data prep

```{r}
wine <- read_csv("data/wine_quality.csv")
```

## Explore wine type

```{r}
ggplot(data = wine,
       aes(x = type)) +
  geom_bar()
```

## Filter by only White wine

```{r}
whitewine <- wine %>%
  filter(type =="white") %>%
  select(c(1:11))
```

# 3. Exploring scatterPlotMatrix

```{r}
scatterPlotMatrix(whitewine,
                  corrPlotType = "Text",
                  distribType = 1,
                  width = 2000,
                  height = 2000)
```


# 4. Exploring parallelPlot
```{r}
set.seed(123)
kmeans4 <- kmeans(whitewine ,4, nstart = 25)
print(kmeans4)
```

```{r}
fviz_cluster(kmeans4, data = whitewine)
```

```{r}
whitewine <- whitewine %>%
  mutate(Cluster =kmeans4$cluster)
```

```{r}
whitewine$Cluster <-
  as_factor(whitewine$Cluster)
```

```{r}
whitewine %>%
  parallelPlot(refColumnDim = "Cluster",
               width = 600,
               height = 600,
               rotateTitle = TRUE)
```
