---
title: "Take-home Exercise 1"
author: "Ha Duc Tien"
date: "April 17, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# 1. Loading the needed libraries

For this take-home exercise 1, I will be using some of the libraries below:

tidyverse patchwork ggrepel ggthemes hrbrthemes ggridges ggdist

```{r}
pacman::p_load(ggrepel, patchwork, 
               ggthemes, hrbrthemes,
               tidyverse, ggridges, ggdist)
```

# 2. Importing the data

Since the data given is a list of csv

```{r}
list_of_files <- list.files(path = "data",
                            recursive = TRUE,
                            pattern = "\\.csv$",
                            full.names = TRUE)
first_quarter_2024 <- read_csv("data/ResidentialTransaction20240414220633.csv")
Realis <- read_csv(list_of_files)
```

```{r}
Realis <- Realis %>% 
  mutate(`Sale Date asDate` = as.Date((parse_date_time(`Sale Date`, 
        orders = c("%d %b %Y")))))
Realis <- Realis %>% 
  mutate(`Sale Month` = format(as.Date((parse_date_time(`Sale Date`, 
        orders = c("%d %b %Y")))), "%b %Y"))

colSums(is.na(Realis))

first_quarter_2024 <- first_quarter_2024 %>% 
  mutate(`Sale Date asDate` = as.Date((parse_date_time(`Sale Date`, 
        orders = c("%d %b %Y")))))

first_quarter_2024 <- first_quarter_2024 %>% 
  mutate(`Sale Month` = format(as.Date((parse_date_time(`Sale Date`, 
        orders = c("%d %b %Y")))), "%b %Y"))
colSums(is.na(first_quarter_2024))
```

```{r}
summary(Realis)
```

```{r}
ggplot(data = Realis, aes(x = `Unit Price ($ PSM)`)) +
  geom_histogram(bins = 20, color = "grey10", fill = "lightblue")+
  ggtitle("Distribution of Unit Price ($PSM)")
```



```{r, fig.width = 20, fig.height = 8, dpi = 300}
plot1 <-ggplot(data = first_quarter_2024, aes(x = `Planning Region`)) +
    geom_bar(color = "grey10", aes(fill = `Property Type`)) +
    ggtitle("Sales by Property Type by Planning Region in the first quarter 2024 ") +
    theme_economist() +
    theme(axis.text=element_text(size = 15), 
          axis.title = element_text(size = 18)
          , title = element_text(size = 20))
```

```{r, fig.width = 20, fig.height = 8, dpi = 300}
plot2 <- ggplot(data = first_quarter_2024, aes(x = `Planning Region`, y = `Unit Price ($ PSM)`)) +
    geom_boxplot(aes(color=`Property Type`)) + 
    # geom_point(stat="summary", fun ="mean", color = "red") +
    theme(axis.text=element_text(size=12)) +
    ggtitle("Monthly changes in Unit Price ($PSM) in first quarter of 2024")+
    theme_economist() +
    theme(axis.text=element_text(size = 15), 
          axis.title = element_text(size = 18)
          , title = element_text(size = 20))
```


```{r, fig.width = 20, fig.height = 8, dpi = 300}

plot3 <- ggplot(data = first_quarter_2024, 
       aes(y = `Planning Region`, x = `Unit Price ($ PSM)`, 
            fill = factor(after_stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient",
    calc_ecdf = TRUE, 
    quantiles = 4,
    quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles") +
  theme_economist()+
  ggtitle("Distribution of Unit Price ($ PSM) by Planning Region in the first quarter 2024")+
  theme(axis.text=element_text(size = 15), 
      axis.title = element_text(size = 18)
      , title = element_text(size = 20))
```

```{r, fig.width = 32, fig.height = 24, dpi = 300}
(plot1 + plot2 ) / plot3
```


```{r, fig.width = 20, fig.height = 8, dpi = 300}
ggplot(data = first_quarter_2024, aes(y = `Area (SQM)`,
                                      x = `Transacted Price ($)`)) +
  geom_point()+
  geom_smooth(method = glm, linewidth = 1) +
  coord_cartesian(ylim = c(30,600), xlim=c(450000,10000000)) +
  geom_label_repel(aes(label = `Postal Code`, color = `Property Type`), 
                   fontface = "bold", max.overlaps = 12) +
  ggtitle("Size (SQM) vs Transacted Price ($) in the first quarter 2024") +
  theme_economist()+
  theme(axis.text=element_text(size = 15), 
    axis.title = element_text(size = 18)
    , title = element_text(size = 20))
```


```{r, fig.width = 20, fig.height = 8, dpi = 300}
plot4 <- ggplot(data = Realis, aes(x = `Sale Month`)) +
    geom_bar(color = "grey10", aes(fill = `Property Type`)) +
    scale_x_discrete(name ="Sale Month", 
                     limits = c("Jan 2023", "Feb 2023", "Mar 2023", 
                        "Apr 2023","May 2023","Jun 2023", 
                        "Jul 2023", "Aug 2023", "Sep 2023",
                        "Oct 2023", "Nov 2023", "Dec 2023", 
                        "Jan 2024", "Feb 2024", "Mar 2024")) +
  
    ggtitle("Monthly number of sales by Property Type") +
    theme_economist() +
    theme(axis.text=element_text(size = 15), 
          axis.title = element_text(size = 18)
          , title = element_text(size = 20), axis)
```

```{r, fig.width = 20, fig.height = 8, dpi = 300}
plot5 <- ggplot(data = Realis, aes(x = `Sale Month`, y = `Unit Price ($ PSM)`)) +
    scale_x_discrete(name ="Sale Month",
                   limits = c("Jan 2023", "Feb 2023", "Mar 2023",
                      "Apr 2023","May 2023","Jun 2023",
                      "Jul 2023", "Aug 2023", "Sep 2023",
                      "Oct 2023", "Nov 2023", "Dec 2023",
                      "Jan 2024", "Feb 2024", "Mar 2024")) +
    
    geom_boxplot(aes(color=`Property Type`)) + 
    # geom_point(stat="summary", fun ="mean", color = "red") +
    theme(axis.text=element_text(size=12)) +
    ggtitle("Monthly changes in Unit Price ($PSM)")+
    theme_economist() +
    theme(axis.text=element_text(size = 15), 
          axis.title = element_text(size = 18)
          , title = element_text(size = 20))
```

```{r, fig.width = 20, fig.height = 8, dpi = 300}
by_month <- Realis %>%
  group_by(`Property Type`, `Sale Month`) %>%
  summarise(`Mean Unit Price ($ PSM)` = mean(`Unit Price ($ PSM)`))

by_month$`Sale Month` <- factor(by_month$`Sale Month`, 
                                levels = c("Jan 2023", "Feb 2023", "Mar 2023",
                                            "Apr 2023","May 2023","Jun 2023",
                                            "Jul 2023", "Aug 2023", "Sep 2023",
                                            "Oct 2023", "Nov 2023", "Dec 2023",
                                            "Jan 2024", "Feb 2024", "Mar 2024"))

by_month <- by_month[order(by_month$`Sale Month`),]


plot6 <- ggplot(data = by_month, aes(x = `Sale Month`, y = `Mean Unit Price ($ PSM)`, 
                            group = `Property Type`)) +
    geom_path(aes(color = `Property Type`), size = 1) +
    geom_point(size = 1.5) +
    theme(axis.text=element_text(size=12))+
    ggtitle("Monthly changes in Mean Unit Price ($PSM) 2023 to first quarter 2024")+
    theme_economist() +
    theme(axis.text=element_text(size = 15), 
        axis.title = element_text(size = 18)
        , title = element_text(size = 20))
```

```{r, fig.width = 20, fig.height = 24, dpi = 300}

(plot4 / plot5/ plot6)
```